services:
  - type: worker
    name: tg-bot-test
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: TG_CHAT_ID
        sync: false
